Repository OSCA-Ado-Ekiti/tech-companies-in-africa, pull requests merged in 2023-10, with the labels that each got.

#82 Added max.ng to Readme.md
  README.md
  src/techCompanies.js
Labels: hacktoberfest-accepted

#99 Sammie
  README.md
  src/techCompanies.js
Labels: hacktoberfest-accepted

#120 Update techCompanies.js
  src/techCompanies.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#124 Update README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#87 feat: add a tech company in africa
  README.md
  src/techCompanies.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#111 Update README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#125 Update techCompanies.js
  src/techCompanies.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#108 added company that starts with C,F and L to the techCompanies.js and READme file
  README.md
  src/techCompanies.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#126 Updated the README.md and techCompanies.js file
  README.md
  src/techCompanies.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#134 Refactor the project
  README.md
  companies/a.md
  companies/b.md
  companies/c.md
  companies/d.md
  companies/e.md
  companies/f.md
  companies/g.md
  companies/h.md
  companies/i.md
  companies/j.md
  companies/k.md
  companies/l.md
  companies/m.md
  companies/n.md
  companies/o.md
  companies/others.md
  companies/p.md
  companies/q.md
  companies/r.md
  companies/s.md
  companies/t.md
  companies/u.md
  companies/v.md
  companies/w.md
  companies/x.md
  companies/y.md
  companies/z.md
  src/assets/landing.png
  src/script.js
  src/techCompanies.js
  src/techCompanies/index.js
  src/techCompanies/orderByAlphabeth/a.js
  src/techCompanies/orderByAlphabeth/b.js
  src/techCompanies/orderByAlphabeth/c.js
  src/techCompanies/orderByAlphabeth/d.js
  src/techCompanies/orderByAlphabeth/e.js
  src/techCompanies/orderByAlphabeth/f.js
  src/techCompanies/orderByAlphabeth/g.js
  src/techCompanies/orderByAlphabeth/h.js
  src/techCompanies/orderByAlphabeth/i.js
  src/techCompanies/orderByAlphabeth/j.js
  src/techCompanies/orderByAlphabeth/k.js
  src/techCompanies/orderByAlphabeth/l.js
  src/techCompanies/orderByAlphabeth/m.js
  src/techCompanies/orderByAlphabeth/n.js
  src/techCompanies/orderByAlphabeth/o.js
  src/techCompanies/orderByAlphabeth/others.js
  src/techCompanies/orderByAlphabeth/p.js
  src/techCompanies/orderByAlphabeth/q.js
  src/techCompanies/orderByAlphabeth/r.js
  src/techCompanies/orderByAlphabeth/s.js
  src/techCompanies/orderByAlphabeth/t.js
  src/techCompanies/orderByAlphabeth/u.js
  src/techCompanies/orderByAlphabeth/v.js
  src/techCompanies/orderByAlphabeth/w.js
  src/techCompanies/orderByAlphabeth/x.js
  src/techCompanies/orderByAlphabeth/y.js
  src/techCompanies/orderByAlphabeth/z.js
Labels: hacktoberfest, hacktoberfest-accepted

#135 Update broken app url
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#136 Update s.js
  src/techCompanies/orderByAlphabeth/s.js
Labels: hacktoberfest, hacktoberfest-accepted

#146 added-quidax
  companies/q.md
  src/techCompanies/orderByAlphabeth/q.js
Labels: hacktoberfest-accepted

#140 Update o.md
  companies/o.md
Labels: hacktoberfest, hacktoberfest-accepted

#141 Update o.js
  src/techCompanies/orderByAlphabeth/o.js
Labels: hacktoberfest, hacktoberfest-accepted

#138 Update t.md
  companies/t.md
Labels: hacktoberfest, hacktoberfest-accepted

#139 Update f.md
  companies/f.md
Labels: hacktoberfest, hacktoberfest-accepted

#144 Feature/Wasoko Adding information on founders
  companies/w.md
  src/techCompanies/orderByAlphabeth/w.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#149 Added Whogohost to the list of tech companies
  companies/w.md
  src/techCompanies/orderByAlphabeth/w.js
Labels: hacktoberfest, hacktoberfest-accepted

#153 added companies with t,x,r,d,c,s and fix companies to right order
  companies/c.md
  companies/d.md
  companies/r.md
  companies/s.md
  companies/t.md
  companies/x.md
  src/techCompanies/orderByAlphabeth/c.js
  src/techCompanies/orderByAlphabeth/d.js
  src/techCompanies/orderByAlphabeth/r.js
  src/techCompanies/orderByAlphabeth/t.js
  src/techCompanies/orderByAlphabeth/x.js
Labels: hacktoberfest-accepted

#154 added irokotv to the readme and techCompanies
  companies/i.md
  src/techCompanies/orderByAlphabeth/i.js
Labels: hacktoberfest, hacktoberfest-accepted

#156 Added Yoco to the company list
  companies/y.md
  src/techCompanies/orderByAlphabeth/y.js
Labels: hacktoberfest-accepted

#159 Updated companies with letter B b.md
  companies/b.md
Labels: hacktoberfest, hacktoberfest-accepted

#160 Update b.js
  src/techCompanies/orderByAlphabeth/b.js
Labels: hacktoberfest, hacktoberfest-accepted

#158 Updated company with letter E e.md
  companies/e.md
Labels: hacktoberfest, hacktoberfest-accepted

#161 Update e.js
  src/techCompanies/orderByAlphabeth/e.js
Labels: hacktoberfest, hacktoberfest-accepted

#157 Updated company with letter A a.md
  companies/a.md
Labels: hacktoberfest, hacktoberfest-accepted

#162 Update a.js
  src/techCompanies/orderByAlphabeth/a.js
Labels: hacktoberfest, hacktoberfest-accepted

#163 added Paga to the readme and techCompanies
  companies/p.md
  src/techCompanies/orderByAlphabeth/p.js
Labels: hacktoberfest, hacktoberfest-accepted

#167 Updated company with letter C c.js
  src/techCompanies/orderByAlphabeth/c.js
Labels: hacktoberfest, hacktoberfest-accepted

#166 Added-PalmPay-To-The-List
  companies/p.md
Labels: hacktoberfest-accepted

#171 Update l.js
  src/techCompanies/orderByAlphabeth/l.js
Labels: hacktoberfest, hacktoberfest-accepted

#174 Added Credpal to the list of companies in both c.md and c.js
  companies/c.md
  src/techCompanies/orderByAlphabeth/c.js
Labels: hacktoberfest, hacktoberfest-accepted

#175 Added to companies with letter B in both b.md and b.js
  companies/b.md
  companies/v.md
  src/techCompanies/orderByAlphabeth/b.js
  src/techCompanies/orderByAlphabeth/v.js
Labels: hacktoberfest, hacktoberfest-accepted

#176 Updated company with letter F
  companies/f.md
  companies/p.md
  src/techCompanies/orderByAlphabeth/f.js
Labels: hacktoberfest, hacktoberfest-accepted

#180 Added a company start with the letter T
  companies/t.md
  src/techCompanies/orderByAlphabeth/t.js
Labels: hacktoberfest, hacktoberfest-accepted

#184 Added to companies starting with B
  companies/b.md
  src/techCompanies/orderByAlphabeth/b.js
Labels: hacktoberfest, hacktoberfest-accepted

#183 Added to companies starting with I
  companies/i.md
  src/techCompanies/orderByAlphabeth/i.js
Labels: hacktoberfest, hacktoberfest-accepted

#182 Companies starting with A
  companies/a.md
  src/techCompanies/orderByAlphabeth/a.js
Labels: hacktoberfest, hacktoberfest-accepted

#188 Added a company starting with the letter B
  companies/b.md
  src/techCompanies/orderByAlphabeth/b.js
Labels: hacktoberfest-accepted

#185 Added Wallets Africa to the companies' list
  companies/w.md
  src/techCompanies/orderByAlphabeth/w.js
Labels: hacktoberfest-accepted

#189 Added p2Vest to the list of companies
  companies/e.md
  companies/p.md
  src/techCompanies/orderByAlphabeth/e.js
  src/techCompanies/orderByAlphabeth/p.js
Labels: hacktoberfest, hacktoberfest-accepted

#191 Added Tribapay to the list of companies
  companies/t.md
  src/techCompanies/orderByAlphabeth/t.js
Labels: hacktoberfest, hacktoberfest-accepted

#195 Added a company starting with A
  companies/a.md
  src/techCompanies/orderByAlphabeth/a.js
Labels: hacktoberfest, hacktoberfest-accepted

#202 Add tech companies Starting with X,D,T,V
  companies/d.md
  companies/t.md
  companies/v.md
  companies/x.md
  src/techCompanies/orderByAlphabeth/d.js
  src/techCompanies/orderByAlphabeth/t.js
  src/techCompanies/orderByAlphabeth/v.js
  src/techCompanies/orderByAlphabeth/x.js
Labels: hacktoberfest, hacktoberfest-accepted

#200 Added Enza Capital, Haba, and Koree to the list of companies
  companies/e.md
  companies/h.md
  companies/k.md
  src/techCompanies/orderByAlphabeth/e.js
  src/techCompanies/orderByAlphabeth/h.js
  src/techCompanies/orderByAlphabeth/k.js
Labels: hacktoberfest, hacktoberfest-accepted

#206 Added ExpandCart, Founders Factory Africa, and Zanifu to the list
  companies/e.md
  companies/f.md
  companies/z.md
  src/techCompanies/orderByAlphabeth/e.js
  src/techCompanies/orderByAlphabeth/f.js
  src/techCompanies/orderByAlphabeth/z.js
Labels: hacktoberfest-accepted

#217 Added a tech company starting with M
  companies/m.md
  src/techCompanies/orderByAlphabeth/m.js
Labels: hacktoberfest, hacktoberfest-accepted

#221 I added Lihon Energy, Cue, and PAL to the list of compnies
  companies/c.md
  companies/l.md
  companies/p.md
  companies/r.md
  src/techCompanies/orderByAlphabeth/c.js
  src/techCompanies/orderByAlphabeth/l.js
  src/techCompanies/orderByAlphabeth/p.js
  src/techCompanies/orderByAlphabeth/r.js
Labels: hacktoberfest, hacktoberfest-accepted

#235 Add Zuri Health
  companies/z.md
  src/techCompanies/orderByAlphabeth/z.js
Labels: hacktoberfest-accepted

#238 Added FlexFin Tx to the list of tech companies
  companies/f.md
  src/techCompanies/orderByAlphabeth/f.js
Labels: hacktoberfest, hacktoberfest-accepted

#239 Added Moringa school to the tech companies
  companies/m.md
  src/techCompanies/orderByAlphabeth/m.js
Labels: hacktoberfest, hacktoberfest-accepted

#241 added katwig and dale legal tech company
  companies/k.md
  src/techCompanies/orderByAlphabeth/k.js
Labels: hacktoberfest, hacktoberfest-accepted

#243 Added a company that starts with letter S
  companies/s.md
  src/techCompanies/orderByAlphabeth/s.js
Labels: hacktoberfest, hacktoberfest-accepted

#245 Affect changes to the akowe company founder's handle
  companies/a.md
  src/techCompanies/orderByAlphabeth/a.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#251 Change the LinkedIn handle added to the VSASF NIG LTD to X handle
  companies/v.md
  src/techCompanies/orderByAlphabeth/v.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
